### ISSUE TITLE
Support for FireFox?

### ISSUE THREAD

**Issue by Samuel-Martineau** [hediet/browser-ext-github-monaco#1]
If I recall correctly, it's quite easy to publish a Chrome extension to FireFox. This extension looks awesome, but as a FireFox user, I'm unable to use it...

**Comment by hediet** [comment]
[Done](https://addons.mozilla.org/de/firefox/addon/monaco-markdown-github-editor/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search).
