### ISSUE TITLE
Improve Completion Of Gemojis

### ISSUE THREAD

**Issue by hediet** [hediet/browser-ext-github-monaco#10]
At this cursor position, Gemoji completion should not be triggered:
```
foo:|
```

**Comment by joaomoreno** [comment]
Oh yeah. I hit this all the time. I really like that the auto suggestion box comes up... unless I'm actually ending a line with `:` and pressing <kbd>Enter</kbd> for a new paragraph. Apparently I do this a lot. 😆

Maybe we could have it automatically come up if the user presses `:` *and* a letter? I wonder if we even support that.

**Comment by hediet** [comment]
Yes, I need to fix this asap :D I'm using ":" quite often too in non-smiley contexts.

> I wonder if we even support that.

You do ;)
There is a command to trigger the suggestion box. So ":" should be disabled as a trigger character and the suggestion box should be triggered by code on text change.

> Or perhaps we can just have :\n be the default suggestion such that pressing Enter will accept it and insert a new line.

I think the suggestion box for smileys should only come up if you actually intend to insert a smiley.

**Comment by joaomoreno** [comment]
![fast](https://media.giphy.com/media/McsdJvL9qrGf9nXh63/giphy.gif)

**Comment by hediet** [comment]
> Maybe we could have it automatically come up if the user presses : and a letter? I wonder if we even support that.

Actually, all it need for showing the box after typing `:` *and* a letter was 150e1262e9d3aaf8bed80944e14161534ae27851 :D I don't know why though. Apparently Monaco uses Magic™.
