### ISSUE TITLE
Whitespace in review comments

### ISSUE THREAD

**Issue by tdamsma** [hediet/browser-ext-github-monaco#14]
Think this shows it clearly, there is too much whitespace

![image](https://user-images.githubusercontent.com/7870803/107497562-0ac55080-6b93-11eb-9332-b3e874602e0d.png)

I suspect this is the culprit:
https://github.com/hediet/browser-ext-github-monaco/blob/43766c8044a866efd3f33868aa1e07b2131ec7c8/src/content-script-main/EditorWrapper.ts#L296

**Comment by hediet** [comment]
Do you use the firefox or chrome extension? I thought I fixed this - the problem is not the spacing, but that GitHub clones HTML nodes, but Monaco does not like to be cloned. I'll look into it.

**Comment by tdamsma** [comment]
This was with the firefox extension, thanks

**Comment by hediet** [comment]
Did the update (0.4.2) fix it?

**Comment by tdamsma** [comment]
Yes, it's gone now! Thanks for making this
