### ISSUE TITLE
Configurable tab stop spaces

### ISSUE THREAD

**Issue by bbugh** [hediet/browser-ext-github-monaco#23]
Hi! 👋 Thanks for this great extension.

I use a lot of ruby and standard ruby formatting is two spaces for tab stops. Unfortunately, this defaults to 4 spaces, which makes it very clumsy to paste and format Ruby code. Is there or can there be a way to configure this? Thanks!

**Comment by hediet** [comment]
Thanks!

Afaik it is very easy to configure the indentation in code, but currently I have no settings infrastructure.

I'm very welcoming contributions!

**Comment by hediet** [comment]
Fixed by #25.

![image](https://user-images.githubusercontent.com/2931520/111883624-c6607800-89bc-11eb-9a34-f5589bc5ce29.png)
