### ISSUE TITLE
Is it possible to prevent autocomplete/autosuggest for plain english words?

### ISSUE THREAD

**Issue by tnorthcutt** [hediet/browser-ext-github-monaco#24]
I love this extension! But, I've noticed that it pops up autocomplete suggestions for what seem like regular words, for lack of a better term.

The README mentions "Autocompletion for issues, mentions and emojis.", so I would not expect the behavior I'm observing. Here's a gif displaying the behavior:

![CleanShot 2021-03-01 at 13 07 41](https://user-images.githubusercontent.com/796639/109552901-98f46e80-7a8f-11eb-8fe8-c8e322a9d80f.gif)

I didn't find any configuration options page or anything that would allow changing this.

Happy to help/provide more information however I can!

**Comment by hediet** [comment]
Fixed with #25.

![image](https://user-images.githubusercontent.com/2931520/111883648-f3148f80-89bc-11eb-9611-0cf079fbe82d.png)
