### ISSUE TITLE
Toggle enable/disable switch in extension menu?

### ISSUE THREAD

**Issue by mickmister** [hediet/browser-ext-github-monaco#35]
Can we have a way to quickly toggle the plugin on and off?

<img width="300px" src="https://user-images.githubusercontent.com/6913320/140009750-b763dc37-990d-40f9-aa22-f31899cdb5f0.png"/>

Maybe we can have it at the top of the options page?

<img width="300px" src="https://user-images.githubusercontent.com/6913320/140010189-f9745352-c945-443e-89b5-34812d007201.png"/>

**Comment by hediet** [comment]
You could switch it on/off here:
![image](https://user-images.githubusercontent.com/2931520/140026310-eb790d5e-72fc-4c32-9399-1215ea63234e.png)

**Comment by mickmister** [comment]
Indeed you can :tada:
