### ISSUE TITLE
Support other websites

### ISSUE THREAD

**Issue by vjpr** [hediet/browser-ext-github-monaco#46]
Would be nice to have on all stackexchange sites like stackoverflow.com.

**Comment by fregante** [comment]
Note for the maintainer: the setup described here would technically allow users to enable the extension on any website: 

- https://github.com/hediet/browser-ext-github-monaco/pull/26#issuecomment-1462444963

However of course you'd need to support/select their `textarea`s as well, so it's not as straightforward.

**Comment by hediet** [comment]
I think this extension should be forked for supporting other sites, as it has a bunch of github specific logic (e.g. mentions and preview) like this:

https://github.com/hediet/browser-ext-github-monaco/blob/f49c3e4825186d5645b251725465cef419ff8393/src/content-script-main/EditorWrapper.ts#L259-L283
