### ISSUE TITLE
Issue with refined-github "add collapsible content" button

### ISSUE THREAD

**Issue by vjpr** [hediet/browser-ext-github-monaco#47]
When using refined-github, the collapsible content button works sporadically.

https://github.com/refined-github/refined-github#writing-comments

[Adds a button to insert collapsible content (via `<details>`).](https://user-images.githubusercontent.com/1402241/53678019-0c721280-3cf4-11e9-9c24-4d11a697f67c.png)

It only works if I click another button first like "add code".

**Comment by tjx666** [comment]
@hediet Also troubled by this issue.

**Comment by hediet** [comment]
Can you investigate what I need to change in this extension?

**Comment by tjx666** [comment]
After investigate the code of this extension, I think maybe this should be fixed in `refined github` side, because this extension only copy the text of textArea: https://github.com/hediet/browser-ext-github-monaco/blob/master/src/content-script-main/EditorWrapper.ts#L163

**Comment by tjx666** [comment]
I had created a issue in refined github repository: https://github.com/refined-github/refined-github/issues/6410

**Comment by hediet** [comment]
Who's up for a PR? ;)

**Comment by tjx666** [comment]
@hediet https://github.com/hediet/browser-ext-github-monaco/pull/52
