### ISSUE TITLE
Intellisense for emojis?

### ISSUE THREAD

**Issue by joaomoreno** [hediet/browser-ext-github-monaco#5]
Eheh, I'm getting very excited with this project!

On the regular GH input box, one can type `:` and get emoji proposals. It would be pretty cool to keep that going in the Monaco editor, to keep the trigger memory going.

Let me know if you'd like a contribution from me, I don't mind helping out.

**Comment by hediet** [comment]
This was not very difficult to implement, but a good opportunity to re-architecture my tokenizer library. Thanks for all these good ideas! 😉
I'll push it to the chrome store soon. The update will also include a markdown preview feature in full screen mode.

**Comment by joaomoreno** [comment]
Dude. 🔥

Another demo in today's standup 😆
